# Generated by Django 5.1.4 on 2024-12-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default=' ')),
                ('category', models.CharField(choices=[('SSB', 'BlushStick'), ('LB', 'Blush'), ('BBP', 'Palette'), ('LP', 'LipPlumper'), ('PH', 'PureHrt'), ('P', 'Power'), ('B', 'Brave'), ('W', 'Worthy'), ('M', 'Midnight'), ('S', 'Spark'), ('A', 'Aqua'), ('Q', 'Sunset'), ('W', 'Wave')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
